volumes:
  postgres-data:

services:
  app:
    container_name: release-wing-java
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_URL: jdbc:postgresql://release-wing-db:5432/postgres

    volumes:
      - ../..:/Release-Wing:cached
      
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: release-wing-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: releasewing

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgadmin:
    image: dpage/pgadmin4
    container_name: release-wing-pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@arrayhive.dev
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - ./pgAdmin-Servers-Release-Wing.json:/pgadmin4/servers.json:ro