site_name: Release-Wing
theme:
  name: mkdocs
  user_color_mode_toggle: true
  nav_style: primary
  highlightjs: true
  hljs_style: a11y-light
  hljs_style_dark: a11y-dark
  hljs_languages:
    - yaml
  navigation_depth: 2
  locale: en
repo_url: https://github.com/ArrayHive/Release-Wing
docs_dir: docs
site_dir: site